# golangci-lint configuration
# Configuration for monorepo with multiple Go modules

run:
  # Timeout for analysis
  timeout: 10m
  
  # Don't build test files
  tests: false

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text
  max-same-issues: 0
  
  # Exclude directories (replaces deprecated run.skip-dirs)
  exclude-dirs:
    - test
    - vendor
    - third_party
    - kitex_gen
    - dal
    - config
  
  # Exclude files (replaces deprecated run.skip-files)
  exclude-files:
    - ".*_test\\.go$"
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
    - ".*/config/.*\\.go$"
    - ".*/dal/.*\\.go$"
    - ".*/kitex_gen/.*\\.go$"
  
  # Exclude specific linters for certain paths
  exclude-rules:
    # Exclude config files
    - path: "(^|/)config/"
      linters:
        - all
    
    # Exclude dal files
    - path: "(^|/)dal/"
      linters:
        - all
    
    # Exclude generated files
    - path: "kitex_gen/"
      linters:
        - all
    
    # Exclude test files from certain checks
    - path: "_test\\.go"
      linters:
        - errcheck
        - gosec
    
    # Ignore cross-module dependency errors
    - text: "could not load export data"
      linters:
        - typecheck
        - govet
        - staticcheck
    
    # Ignore import errors from cross-module dependencies
    - text: "could not import"
      linters:
        - typecheck

linters:
  # Disable all linters by default
  disable-all: true
  
  # Enable only basic linters that don't require full type checking
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - unused
  
  # Explicitly disable linters that cause issues in monorepo
  disable:
    - govet        # Requires full type information
    - staticcheck  # Requires full type information
    - typecheck    # Cannot resolve cross-module dependencies

linters-settings:
  errcheck:
    # Don't check for errors in defer
    check-type-assertions: false
    check-blank: false
  
  gosimple:
    # Don't check for simplifications that require type info
    checks: ["all"]

