# golangci-lint configuration - Minimal config for monorepo

run:
  timeout: 5m
  tests: false

linters:
  disable-all: true
  enable:
    - errcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Ignore all issues in these paths
    - path: ".*_test\\.go"
    - path: ".*/config/.*"
    - path: ".*/dal/.*"
    - path: "kitex_gen/.*"
    - path: ".*\\.pb\\.go"
    
    # Ignore specific errors
    - text: "could not load export data"
    - text: "could not import"

