# golangci-lint configuration
# Exclude config files from linting due to monorepo dependency resolution issues

run:
  # Timeout for analysis
  timeout: 5m
  
  # Skip directories
  skip-dirs:
    - test
    - vendor
    - third_party
  
  # Skip files
  skip-files:
    - ".*config/config\\.go$"
    - ".*config/yaml_parser\\.go$"
    - "game/config/config.go"
    - "game/config/yaml_parser.go"
    - "game_platform_api/config/config.go"
    - "game_platform_api/config/yaml_parser.go"
    - "cp_center/config/config.go"

issues:
  # Exclude specific linters for config files
  exclude-rules:
    - path: ".*config/config\\.go"
      linters:
        - typecheck
        - errcheck
        - gosimple
        - govet
        - staticcheck
        - unused
    
    - path: ".*config/yaml_parser\\.go"
      linters:
        - typecheck
        - errcheck
        - gosimple
        - govet
        - staticcheck
        - unused
    
    # Exclude ioutil deprecation warning (if using Go 1.16+)
    - path: ".*config/.*\\.go"
      text: "ioutil is deprecated"

linters:
  # Enable specific linters (adjust based on your needs)
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  
  # Disable problematic linters for config files
  disable:
    - typecheck  # Disable for files with external dependencies

