// Code generated by hertz generator.

package game_platform_api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gamesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getgamelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getgamedetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updategamedetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reviewgameversionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _creategamedetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cpMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _materialsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createcpmaterialMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcpmaterialMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatecpmaterialMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reviewcpmaterialMw() []app.HandlerFunc {
	// your code...
	return nil
}
