// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	game_platform_api "github.com/GameLaunchPad/game_management_project/game_platform_api/biz/router/game_platform_api"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	game_platform_api.Register(r)
}
